UPDATE ESTADOS
SET NOME = 'Maranhã'
WHERE SIGLA = 'MA';

SELECT EST.NOME FROM ESTADOS EST WHERE SIGLA = 'MA';

UPDATE ESTADOS
SET NOME = 'Paraná',
	POPULACAO = 11.32
WHERE SIGLA = 'PR';

SELECT EST.NOME, SIGLA, POPULACAO FROM ESTADOS EST WHERE SIGLA = 'PR';