SELECT 
	E.NOME AS ESTADO, 
    C.NOME AS CIDADE, 
    REGIAO AS REGIÃO
FROM ESTADOS E, CIDADES C
WHERE E.ID = C.ESTADO_ID;

SELECT 
	C.NOME AS CIDADE,
	E.NOME AS ESTADO, 
    REGIAO AS REGIÃO
FROM ESTADOS E
INNER JOIN CIDADES C ON E.ID = C.ESTADO_ID;