-- POPULAÇÃO TOTAL POR ESTADO
SELECT REGIAO AS 'REGIÃO', SUM(POPULACAO) AS TOTAL
FROM ESTADOS
GROUP BY REGIAO
ORDER BY TOTAL DESC;

-- SOMA DA POPULACÃO DE TODOS OS ESTADOS
SELECT SUM(POPULACAO) AS TOTAL
FROM ESTADOS;

-- MÉDIA DE POPULAÇÃO POR ESTADO
SELECT AVG(POPULACAO) AS TOTAL
FROM ESTADOS;