CREATE TABLE IF NOT EXISTS PREFEITOS (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    CIDADE_ID INT UNSIGNED,
    PRIMARY KEY (ID),
    UNIQUE KEY (CIDADE_ID),
    FOREIGN KEY (CIDADE_ID) REFERENCES CIDADES (ID)
);