SELECT * FROM ESTADOS;

INSERT INTO CIDADES (NOME, AREA, ESTADO_ID)
VALUES ('Campinas', 795, 28);

INSERT INTO CIDADES (NOME, AREA, ESTADO_ID)
VALUES ('Niterói', 133.9, 22);

INSERT INTO 
	CIDADES (NOME, AREA, ESTADO_ID)
VALUES (
	'Caruaru',
    920.6,
    (SELECT ID FROM ESTADOS WHERE SIGLA = 'PE')
);

INSERT INTO 
	CIDADES (NOME, AREA, ESTADO_ID)
VALUES (
	'Juazeiro do Norte',
    248.2,
    (SELECT ID FROM ESTADOS WHERE SIGLA = 'CE')
);

SELECT * FROM CIDADES;