version: '3.9'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.28 # https://hub.docker.com/_/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - 3306:3306